"""
Django settings for dynamic_forms project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['*'] if DEBUG else config("ALLOWED_HOSTS").split(",")

# ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",")
# print("ALLOWED_HOSTS =", ALLOWED_HOSTS)

INTERNAL_API_BASE_URL = os.environ.get("INTERNAL_API_BASE_URL", "http://127.0.0.1:8000")



# Application definition

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',  # Put corsheaders early in the list
    'system_management',
    'question_management',
    'application_management',
    'form_portal_management',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'dynamic_forms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dynamic_forms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        
        

    ),
    'EXPIRY_MINUTES': 30,  # Token will expire after 30 minutes

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'system_management.User'


# # # CORS Configuration
# # CORS_ALLOW_CREDENTIALS = True
# # CORS_ALLOW_ALL_ORIGINS = False  # Keep False for security

# # # Define allowed origins based on environment
# # DEBUG = config('DEBUG', default=False, cast=bool)

# # if DEBUG:
# #     # Development origins
# #     CORS_ALLOWED_ORIGINS = [
# #         # "http://localhost:3000",
# #         # "http://127.0.0.1:3000",
# #         "http://dynamicz3.s3-website-us-east-1.amazonaws.com"
# #         "http://localhost:8000",
# #         "http://127.0.0.1:8000",
# #     ]
# # else:
# #     # Production origins
# #     CORS_ALLOWED_ORIGINS = [
# #         "http://dynamicz3.s3-website-us-east-1.amazonaws.com",
# #         "https://dynamicz3.s3-website-us-east-1.amazonaws.com",  # Add HTTPS version too
# #         "http://3.144.218.251",
# #         "http://52.14.111.23",
# #         # Add development origins for testing in production
# #         # "http://localhost:3000",
# #         # "http://127.0.0.1:3000",
# #         "http://dynamicz3.s3-website-us-east-1.amazonaws.com",


# #     ]

# # CORS Configuration
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_ORIGINS = False  # Keep False for security

# # Define allowed origins based on environment
# DEBUG = config('DEBUG', default=False, cast=bool)

# if DEBUG:
#     # Development origins
#     origins_set = {
#         "http://localhost:3000",
#         "http://127.0.0.1:3000",
#         # "http://dynamicz3.s3-website-us-east-1.amazonaws.com",
#         "http://localhost:8000",
#         "http://127.0.0.1:8000",
#     }
# else:
#     # Production origins
#     origins_set = {
#         "http://dynamicz3.s3-website-us-east-1.amazonaws.com",
#         # "https://dynamicz3.s3-website-us-east-1.amazonaws.com",
#         "http://3.144.218.251",
#         "http://52.14.111.23",
#         # Add development origins for testing in production
#         "http://localhost:3000",
#         "http://127.0.0.1:3000",
#     }

# # Convert the set back to a list
# CORS_ALLOWED_ORIGINS = list(origins_set)


# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]

# CORS_EXPOSE_HEADERS = [
#     "Content-Type", 
#     "X-CSRFToken"
# ]

# # CSRF Configuration
# CSRF_COOKIE_SECURE = not DEBUG  # True in production, False in development
# CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript access
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_NAME = "csrftoken"
# CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
# CSRF_USE_SESSIONS = False

# # CSRF Trusted Origins (same as CORS allowed origins)
# CSRF_TRUSTED_ORIGINS = [
#     "http://dynamicz3.s3-website-us-east-1.amazonaws.com",
#     "https://dynamicz3.s3-website-us-east-1.amazonaws.com",
#     # "http://localhost:3000",
#     # "http://127.0.0.1:3000",
#     "http://127.0.0.1:8000",
#     "http://localhost:8000",
#     "http://3.144.218.251",
#     "http://52.14.111.23",
# ]

# # Session Configuration
# SESSION_COOKIE_SECURE = not DEBUG  # True in production, False in development
# SESSION_COOKIE_SAMESITE = "Lax"

# # Security Settings
# X_FRAME_OPTIONS = 'ALLOWALL'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Changed to https
# SECURE_SSL_REDIRECT = False

# CORS Configuration
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False


# Define allowed origins based on environment
DEBUG = config('DEBUG', default=False, cast=bool)

if DEBUG:
    # Development origins
    allowed_origins = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
else:
    # Production origins
    allowed_origins = [
        "http://dynamicz3.s3-website-us-east-1.amazonaws.com",
        "http://3.144.218.251",
        "http://52.14.111.23",
    ]

# Set both CORS and CSRF to use the same origins
CORS_ALLOWED_ORIGINS = allowed_origins
CSRF_TRUSTED_ORIGINS = allowed_origins

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = [
    "Content-Type", 
    "X-CSRFToken"
]

# CSRF Configuration
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_USE_SESSIONS = False

# Session Configuration
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"

# Security Settings
X_FRAME_OPTIONS = 'ALLOWALL'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False


# External Services
BACK_BLAZE_KEY_ID = config('BACK_BLAZE_KEY_ID')
BACK_BLAZE_KEY_NAME = config('BACK_BLAZE_KEY_NAME')
BACK_BLAZE_BUCKET_NAME = config('BACK_BLAZE_BUCKET_NAME')
BACK_BLAZE_APLLICATION_KEY = config('BACK_BLAZE_APLLICATION_KEY')
OPEN_AI_API_KEY = config('OPEN_AI_API_KEY')
CLAUDE_AI_API_KEY = config('CLAUDE_AI_API_KEY')
# FRONTEND_URL = 'http://localhost:3000'  # change to production URL when deploying
SENDGRID_API_KEY = config("SENDGRID_API_KEY")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# # Session and CSRF Security
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = False  # Change to True in production with HTTPS
# CSRF_COOKIE_HTTPONLY = False
# CSRF_COOKIE_SAMESITE = 'Lax'  # Or 'Strict'/'None' based on your use case
# CSRF_COOKIE_NAME = "csrftoken"
# CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
# CSRF_USE_SESSIONS = False


# CORS_ALLOW_CREDENTIALS = True
# # CORS_ORIGIN_ALLOW_ALL = False  # Good for security
# # Or for development, you can use:
# # CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_ALL_ORIGINS = False  # Set to False to use specific origins
# # CORS_ALLOWED_ORIGINS = [
# #     "http://localhost:3000",
# #     "http://127.0.0.1:3000",
# #     "http://localhost:3000",
# #     "http://52.14.111.23",
# #     "http://3.144.218.251",
# #     "http://dynamicz3.s3-website-us-east-1.amazonaws.com",

# #   # Your Next.js dev server
    
    
# # ]
# # Ensure CSRF settings match your production environment
# CSRF_COOKIE_SECURE = False  # Set to True when using HTTPS
# CSRF_COOKIE_HTTPONLY = True # Best practice for security
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://3.144.218.251",
#     "http://dynamicz3.s3-website-us-east-1.amazonaws.com",
# ]

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://127.0.0.1:8000",
#     "http://localhost:8000",
#     "http://56.228.24.233",
#     "http://52.14.111.23",
#     "http://3.144.218.251",
#     'http://3.144.218.251',
#     "http://dynamicz3.s3-website-us-east-1.amazonaws.com",


# ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]


# # If using HTTPS in production, also add:
# # "https://dynamicz3.s3-website-us-east-1.amazonaws.com",

# CORS_ALLOW_CREDENTIALS = True  # Important for sending cookies cross-domain
# X_FRAME_OPTIONS = 'ALLOWALL'



# # If you need to expose specific headers:
# CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

# # Tell Django it's behind a trusted proxy (NGINX)
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')

# # Ensure you're not forcing SSL unless you're using HTTPS via AWS ACM/Load Balancer
# SECURE_SSL_REDIRECT = False

# #for dhango cross site  settings

# SESSION_COOKIE_SAMESITE = "Lax"
# SESSION_COOKIE_SECURE = False



# # BACKBLAZE
# BACK_BLAZE_KEY_ID = config('BACK_BLAZE_KEY_ID')
# BACK_BLAZE_KEY_NAME = config('BACK_BLAZE_KEY_NAME')
# BACK_BLAZE_BUCKET_NAME = config('BACK_BLAZE_BUCKET_NAME')
# BACK_BLAZE_APLLICATION_KEY =config('BACK_BLAZE_APLLICATION_KEY')
# OPEN_AI_API_KEY = config('OPEN_AI_API_KEY')
# CLAUDE_AI_API_KEY = config('CLAUDE_AI_API_KEY')