# Generated by Django 5.0.8 on 2025-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_portal_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.CharField(max_length=1024),
        ),
    ]
