# Generated by Django 5.0.8 on 2025-06-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0007_formresponse_category_formresponse_created_at_and_more'),
        ('form_portal_management', '0002_alter_document_file'),
        ('question_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_management.maincategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_management.question'),
        ),
    ]
