# Generated by Django 5.0.8 on 2025-04-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formquestionassignment',
            old_name='case_form_type',
            new_name='form_type',
        ),
    ]
