# Generated by Django 5.0.8 on 2025-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0003_formsubmission_formresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='categories',
            field=models.ManyToManyField(blank=True, to='application_management.maincategory'),
        ),
    ]
