# Generated by Django 5.0.8 on 2025-05-07 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0004_formtype_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_management.formtype')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_management.maincategory')),
            ],
            options={
                'unique_together': {('form_type', 'main_category')},
            },
        ),
    ]
