# Generated by Django 5.0.8 on 2025-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0005_formcategoryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
