# Generated by Django 5.0.8 on 2025-06-04 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0006_maincategory_is_active'),
        ('question_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_management.maincategory'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application_management.formtype'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='response_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='response_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_management.option'),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('submission', 'form_type', 'category', 'question')},
        ),
    ]
