# Generated by Django 5.0.8 on 2026-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0008_formsubmission_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
