# Generated by Django 5.0.8 on 2026-05-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_management', '0009_formsubmission_review_notes'),
        ('system_management', '0002_organisation_user_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtype',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='formtype',
            name='date_created',
        ),
        migrations.AddField(
            model_name='formtype',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='system_management.organisation'),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
